name: Daily Tag Site

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: 'https://github.com/hosted-everything/ant-design-charts.git'
  # Required, token to authenticate bot, could use ${{ secrets.GITHUB_TOKEN }}
  # Over here, we use a PAT instead to authenticate workflow file changes.
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  # Optional, defaults to main
  UPSTREAM_BRANCH: 'v2'
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: ''
  # Optional fetch arguments
  FETCH_ARGS: ''
  # Optional merge arguments
  MERGE_ARGS: '--no-ff'
  # Optional push arguments
  PUSH_ARGS: ''
  # Optional toggle to spawn time logs (keeps action active)
  SPAWN_LOGS: 'false' # "true" or "false"

on:
  schedule:
    - cron: '0 7 * * *' # ron on 7am every day
  # Allows manual workflow run (must in default branch to work)
  push:
    branches:
      - v2
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          token: ${{ env.WORKFLOW_TOKEN }}
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}

  build-site:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Switch to site branch
        run: git checkout -b gh-pages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_STORE
      - name: install dependencies
        run: pnpm install

      - name: add content path
        run: |
          sed -i 's/scripts: \[\],/scripts: \[\], manifest: {basePath: "\/mirror\/ant-charts\/",}, base: "\/mirror\/ant-charts\/", publicPath: "\/mirror\/ant-charts\/"/' ./site/.dumirc.ts
      - name: build site
        run: |
          pnpm run build:lib
          pnpm run build:site

      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ant-charts.zip dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::ant-charts_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ant-charts.zip
